export const skillCategories = {
  Frontend: [
    "React",
    "Vue.js",
    "Angular",
    "JavaScript",
    "TypeScript",
    "HTML5",
    "CSS3",
    "Next.js",
    "Nuxt.js",
    "Svelte",
    "jQuery",
    "Bootstrap",
    "Tailwind CSS",
    "Material-UI",
    "Ant Design",
    "Styled Components",
    "SASS/SCSS",
  ],
  Backend: [
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "Flask",
    "Java",
    "Spring Boot",
    "C#",
    ".NET Core",
    "PHP",
    "Laravel",
    "Ruby on Rails",
    "Go",
    "Rust",
    "FastAPI",
    "NestJS",
    "Koa.js",
  ],
  Database: [
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Redis",
    "SQLite",
    "Oracle",
    "Microsoft SQL Server",
    "Firebase",
    "Supabase",
    "DynamoDB",
    "Cassandra",
    "Neo4j",
    "InfluxDB",
  ],
  "DevOps & Cloud": [
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud",
    "Jenkins",
    "GitLab CI",
    "GitHub Actions",
    "Terraform",
    "Ansible",
    "Linux",
    "Nginx",
    "Apache",
    "Microservices",
    "Serverless",
  ],
  Mobile: [
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Ionic",
    "Xamarin",
    "Native Android",
    "Native iOS",
    "Cordova",
    "Unity",
  ],
  "Tools & Others": [
    "Git",
    "Webpack",
    "Vite",
    "ESLint",
    "Prettier",
    "Jest",
    "Cypress",
    "Postman",
    "Figma",
    "Adobe XD",
    "Photoshop",
    "Jira",
    "Trello",
    "Slack",
    "VS Code",
    "IntelliJ IDEA",
  ],
  "Data Science": [
    "Python",
    "R",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Jupyter",
    "Machine Learning",
    "Deep Learning",
    "Data Analysis",
    "Statistics",
  ],
};